<a href="https://colab.research.google.com/github/Harideep18/Diagon-Alley/blob/main/Digital_Diagnosis_for_Infectious_Diseases.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Training.csv')
x_train = dataset.iloc[:, :-1].values
y_train = dataset.iloc[:, -1].values
dataset1 = pd.read_csv('Testing.csv')
x_test = dataset1.iloc[:, :-1].values
y_test = dataset1.iloc[:, -1].values


In [ ]:
print(x_train)

[[1 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 1 1 1]]


In [ ]:
print(y_train)

['Fungal infection' 'Fungal infection' 'Fungal infection' ...
 'Urinary tract infection' 'Psoriasis' 'Impetigo']


In [ ]:
print(x_test)

[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 1 1 1]
 [1 1 0 ... 0 1 0]]


In [ ]:
print(y_test)

['Fungal infection' 'Allergy' 'GERD' 'Chronic cholestasis'
 'Peptic ulcer disease' 'AIDS' 'Gastroenteritis' 'Bronchial Asthma'
 'Cervical spondylosis' 'Jaundice' 'Malaria' 'Chicken pox' 'Dengue'
 'Typhoid' 'hepatitis A' 'Hepatitis B' 'Hepatitis C' 'Hepatitis D'
 'Hepatitis E' 'Alcoholic hepatitis' 'Tuberculosis' 'Common Cold'
 'Pneumonia' 'Dimorphic hemmorhoids' 'Varicose veins' 'Hypothyroidism'
 'Hyperthyroidism' 'Hypoglycemia' 'Osteoarthristis' 'Arthritis'
 'Paroxysmal  Positional Vertigo' 'Acne' 'Urinary tract infection'
 'Psoriasis' 'Impetigo' 'Fungal infection']


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[ 2.47991935  2.26463494  6.53409859 ... -0.15733944 -0.15733944
  -0.15733944]
 [-0.40323892  2.26463494  6.53409859 ... -0.15733944 -0.15733944
  -0.15733944]
 [ 2.47991935 -0.44157227  6.53409859 ... -0.15733944 -0.15733944
  -0.15733944]
 ...
 [-0.40323892 -0.44157227 -0.1530433  ... -0.15733944 -0.15733944
  -0.15733944]
 [-0.40323892  2.26463494 -0.1530433  ... -0.15733944 -0.15733944
  -0.15733944]
 [-0.40323892  2.26463494 -0.1530433  ...  6.3556854   6.3556854
   6.3556854 ]]


In [ ]:
print(x_test)

[[ 2.47991935  2.26463494  6.53409859 ... -0.15733944 -0.15733944
  -0.15733944]
 [-0.40323892 -0.44157227 -0.1530433  ... -0.15733944 -0.15733944
  -0.15733944]
 [-0.40323892 -0.44157227 -0.1530433  ... -0.15733944 -0.15733944
  -0.15733944]
 ...
 [-0.40323892  2.26463494 -0.1530433  ... -0.15733944 -0.15733944
  -0.15733944]
 [-0.40323892  2.26463494 -0.1530433  ...  6.3556854   6.3556854
   6.3556854 ]
 [ 2.47991935  2.26463494 -0.1530433  ... -0.15733944  6.3556854
  -0.15733944]]


## Training the K-NN model on the Training set

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Fungal infection' 'Fungal infection']
 ['Allergy' 'Allergy']
 ['GERD' 'GERD']
 ['Chronic cholestasis' 'Chronic cholestasis']
 ['Peptic ulcer diseae' 'Peptic ulcer disease']
 ['AIDS' 'AIDS']
 ['Gastroenteritis' 'Gastroenteritis']
 ['Bronchial Asthma' 'Bronchial Asthma']
 ['Cervical spondylosis' 'Cervical spondylosis']
 ['Jaundice' 'Jaundice']
 ['Malaria' 'Malaria']
 ['Chicken pox' 'Chicken pox']
 ['Dengue' 'Dengue']
 ['Typhoid' 'Typhoid']
 ['hepatitis A' 'hepatitis A']
 ['Hepatitis B' 'Hepatitis B']
 ['Hepatitis C' 'Hepatitis C']
 ['Hepatitis D' 'Hepatitis D']
 ['Hepatitis E' 'Hepatitis E']
 ['Alcoholic hepatitis' 'Alcoholic hepatitis']
 ['Tuberculosis' 'Tuberculosis']
 ['Common Cold' 'Common Cold']
 ['Pneumonia' 'Pneumonia']
 ['Dimorphic hemmorhoids(piles)' 'Dimorphic hemmorhoids']
 ['Varicose veins' 'Varicose veins']
 ['Hypothyroidism' 'Hypothyroidism']
 ['Hyperthyroidism' 'Hyperthyroidism']
 ['Hypoglycemia' 'Hypoglycemia']
 ['Osteoarthristis' 'Osteoarthristis']
 ['Arthritis' 'Arth

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


0.8888888888888888

## Predicting the Disease

In [ ]:
q=list(map(int,input().split()))
print(q)

0	0	0	0	0	0	1	0	0	0	0	1	0	0	1	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0	0	0	1	1	1	1	0	0	0	1	0	0	0	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
a=classifier.predict(sc.transform([q]))
print(a)

['Hepatitis E']


# Suggesting Description to the predicted disease
```



In [ ]:
dataset2=pd.read_csv('description.csv')
disease=dataset2.iloc[:, :1].values
description=dataset2.iloc[:,1].values

In [ ]:
if(a[0] in disease):
  b=np.where(disease==a[0])
  print(description[b[0]])
else:
  print('Disease not found')

['A rare form of liver inflammation caused by infection with the hepatitis E virus (HEV). It is transmitted via food or drink handled by an infected person or through infected water supplies in areas where fecal matter may get into the water. Hepatitis E does not cause chronic liver disease.']


# Suggesting Precautions to be followed for the predicted Disease

In [ ]:
dataset3=pd.read_csv('precautions.csv')
diseases=dataset3.iloc[:, :1].values
precaution=dataset3.iloc[:,1:].values

In [ ]:
if(a[0] in diseases):
  c=np.where(diseases==a[0])
  print(precaution[c[0], :])

[['stop alcohol consumption' 'rest' 'consult doctor' 'medication']]
